import { useEffect, useRef, useState, type ReactNode } from 'react';
import { ArrowDownToLine, ArrowLeft, ArrowRight, BookOpen, Check, CheckCheck, ChevronRight, CircleHelp, Clock3, Compass, Download, Expand, Eye, Flag, FolderOpen, Globe2, Keyboard, Lightbulb, LockKeyhole, Map, MapPin, MoreHorizontal, PackageOpen, Play, RotateCcw, Save, Search, Settings2, ShieldCheck, Sparkles, Volume2, VolumeX, Wrench, X } from 'lucide-react';
import { Scene } from './components/Scene';
import { ItemArt, Pin, Tuto } from './components/Characters';
import { useGame } from './game/useGame';
import { formatTime, loadSettings, restoreBackup, saveSettings, startAmbience, type Settings } from './game/state';
import { endings, regions, stages, validateStages } from './game/stages';

type Panel='journal'|'map'|'settings'|'hint'|'help'|'inventory'|'save'|null;
function Modal({title,eyebrow,children,onClose,wide=false}:{title:string;eyebrow:string;children:ReactNode;onClose:()=>void;wide?:boolean}){
 const ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const old=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.querySelector<HTMLButtonElement>('button')?.focus();return()=>{document.body.style.overflow=old;previous?.focus();};},[]);
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><div className={`modal ${wide?'modal-wide':''}`} ref={ref} role="dialog" aria-modal="true" aria-label={title} onKeyDown={e=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const nodes=ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a,input,select,[tabindex="0"]');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}}><div className="modal-header"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div><button className="icon-button modal-close" onClick={onClose} aria-label="닫기"><X size={21}/></button></div>{children}</div></div>;
}
function Toggle({label,description,checked,onChange}:{label:string;description:string;checked:boolean;onChange:()=>void}){return <button className="setting-toggle" role="switch" aria-checked={checked} onClick={onChange}><span><strong>{label}</strong><small>{description}</small></span><span className={`toggle ${checked?'on':''}`}><i/></span></button>;}
export default function App(){
 const [settings,setSettings]=useState<Settings>(loadSettings);
 const g=useGame(settings);
 const [panel,setPanel]=useState<Panel>(null);
 const [journalTab,setJournalTab]=useState<'evidence'|'memories'>('evidence');
 const [journalSearch,setJournalSearch]=useState('');
 const [confirmReset,setConfirmReset]=useState(false);
 const [downloading,setDownloading]=useState(0);
 const [isFullscreen,setFullscreen]=useState(false);
 const inventoryRef=useRef<HTMLDivElement>(null);
 const ko=settings.language==='ko';
 const region=regions[g.stage.regionId-1];
 const completeCount=Object.values(g.data.progress).filter(p=>p.completed).length;
 const maxStage=Math.max(...Object.keys(g.data.progress).map(Number));
 const close=()=>setPanel(null);
 const setting=<K extends keyof Settings>(key:K,value:Settings[K])=>setSettings(s=>({...s,[key]:value}));
 useEffect(()=>{saveSettings(settings);},[settings]);
 useEffect(()=>{if(settings.music)return startAmbience();},[settings.music]);
 useEffect(()=>{if('serviceWorker' in navigator)void navigator.serviceWorker.register('/sw.js').catch(()=>{});},[]);
 useEffect(()=>{const handler=()=>setFullscreen(Boolean(document.fullscreenElement));document.addEventListener('fullscreenchange',handler);return()=>document.removeEventListener('fullscreenchange',handler);},[]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.matches('input,textarea,select')||e.ctrlKey||e.metaKey||e.altKey)return;if(e.key==='Escape'){close();return;}if(panel||g.ending!==null)return;const k=e.key.toLowerCase();if(k==='h'){g.hint();setPanel('hint');}if(k==='j')setPanel('journal');if(k==='m')setPanel('map');if(k==='i')setPanel('inventory');if(k==='e')g.inspect();if(k===' '&&e.target===document.body){e.preventDefault();setting('showHotspots',!settings.showHotspots);}if(k==='?'||k==='F1'){e.preventDefault();setPanel('help');}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[g,panel,settings.showHotspots]);
 const fullscreen=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{g.notify('이 브라우저에서는 전체 화면을 지원하지 않습니다.');}};
 const downloadRegion=async(all=false)=>{if(!('caches' in window)){g.notify('이 브라우저에서는 오프라인 저장을 지원하지 않습니다.');return;}setDownloading(1);try{const cache=await caches.open('deceptive-guide-v1');const urls=all?regions.map((_,i)=>`/images/region-${i+1}.jpg`):[g.stage.backgroundBundle];await cache.addAll(['/','/index.html','/manifest.webmanifest','/icon.svg']);for(let i=0;i<urls.length;i++){await cache.add(urls[i]);setDownloading(Math.round((i+1)/urls.length*100));}g.notify(all?'10개 지역의 오프라인 다운로드가 완료되었습니다.':'현재 지역을 오프라인에서 플레이할 수 있습니다.');}catch{g.notify('다운로드를 완료하지 못했습니다. 연결 상태와 저장 공간을 확인하세요.');}finally{setDownloading(0);}};
 const openHint=()=>{g.hint();setPanel('hint');};
 return <div className={`app ${settings.contrast?'high-contrast':''} ${settings.reduced?'reduced-motion':''} ${settings.largeText?'large-text':''}`}>
 <header className="site-header"><a className="brand" href="#adventure" onClick={e=>{e.preventDefault();close();}} aria-label="거짓말하는 튜토리얼 홈"><span className="brand-mark"><Compass size={26} strokeWidth={1.4}/></span><span><strong>거짓말하는 튜토리얼<span className="brand-period">.</span></strong><small>DECEPTIVE GUIDE</small></span></a>
 <nav className="main-nav" aria-label="게임 메뉴"><button className={panel===null?'active':''} onClick={close}><Compass size={17}/>{ko?'모험':'Adventure'}<span className="nav-active-dot"/></button><button className={panel==='journal'?'active':''} onClick={()=>setPanel('journal')}><BookOpen size={17}/>{ko?'정비 일지':'Journal'}{g.data.evidence.length>0&&<span className="nav-count">{g.data.evidence.length}</span>}</button><button className={panel==='map'?'active':''} onClick={()=>setPanel('map')}><Map size={17}/>{ko?'지역 지도':'World map'}</button></nav>
 <div className="header-actions"><button className="save-indicator" onClick={()=>setPanel('save')}><span className={g.saved?'saved-dot':'saving-dot'}/><span>{g.saved?(ko?'자동 저장됨':'Saved'):(ko?'저장 중…':'Saving…')}</span></button><span className="header-divider"/><button className="icon-button" onClick={()=>setting('sound',!settings.sound)} aria-label={settings.sound?'효과음 끄기':'효과음 켜기'} title={settings.sound?'효과음 끄기':'효과음 켜기'}>{settings.sound?<Volume2 size={19}/>:<VolumeX size={19}/>}</button><button className={`icon-button ${panel==='settings'?'selected':''}`} onClick={()=>setPanel('settings')} aria-label="설정"><Settings2 size={19}/></button></div>
 </header>
 <main id="adventure" className="main-content">
 <section className="stage-heading"><div className="stage-heading-left"><span className="chapter-number">{String(g.stage.regionId).padStart(2,'0')}</span><div><div className="breadcrumb"><span>{ko?`CHAPTER ${String(g.stage.regionId).padStart(2,'0')}`:region.en}</span><span className="breadcrumb-line"/><span>{ko?region.name:region.en}</span></div><h1>{ko?g.stage.title:g.stage.translations.en.title}</h1></div></div><div className="stage-heading-right"><span className="stage-pill"><span className="tiny-diamond"/>{ko?'스테이지':'STAGE'} <strong>{String(g.data.stage).padStart(2,'0')}</strong><span>/ 50</span></span><button className="icon-button" onClick={fullscreen} title={isFullscreen?'전체 화면 종료':'전체 화면'} aria-label="전체 화면 전환"><Expand size={18}/></button><button className="icon-button desktop-help" onClick={()=>setPanel('help')} title="플레이 방법" aria-label="플레이 방법"><CircleHelp size={18}/></button></div></section>
 <Scene game={g} settings={settings} onHints={openHint} onToggleHotspots={()=>setting('showHotspots',!settings.showHotspots)}/>
 <section className={`inventory-bar ${g.selectedItem?'has-selection':''}`} aria-label="인벤토리"><button className="inventory-title" onClick={()=>setPanel('inventory')}><span className="inventory-title-icon"><PackageOpen size={20}/></span><span><strong>{ko?'인벤토리':'Inventory'}</strong><small>{g.data.inventory.length}개의 소지품</small></span><kbd>I</kbd></button><div className="inventory-items" ref={inventoryRef}>{Array.from({length:Math.max(7,g.data.inventory.length)},(_,index)=>{const item=g.data.inventory[index];return item?<button key={index} className={`inventory-slot ${g.selectedItem===item?'selected':''}`} onClick={()=>{if(item==='정비 수첩'){setPanel('journal');return;}g.selectItem(item);}} title={`${item} · 클릭해서 선택`} aria-label={`${item} ${g.selectedItem===item?'선택됨':'선택'}`} aria-pressed={g.selectedItem===item}><span className="slot-number">{index+1}</span><ItemArt name={item}/><span className="item-tooltip">{item}</span>{g.selectedItem===item&&<span className="selected-check"><Check size={10}/></span>}</button>:<div className="inventory-slot empty" key={index}><span className="slot-number">{index+1}</span><span className="empty-cross">+</span></div>;})}</div><button className="inventory-more icon-button" onClick={()=>setPanel('inventory')} aria-label="모든 소지품 보기"><MoreHorizontal size={20}/></button><div className="memory-counter"><span className="memory-icon"><Sparkles size={19}/></span><span><small>{ko?'기억 조각':'Memories'}</small><strong>{String(g.data.logs.length).padStart(2,'0')} <span>/ 50</span></strong></span></div></section>
 <div className="under-inventory">{g.selectedItem?<span className="selected-item-note"><Wrench size={13}/><strong>{g.selectedItem}</strong> 선택됨 · 장면 속 대상에 클릭해 사용하세요.<button onClick={()=>g.selectItem(g.selectedItem!)}><X size={12}/> 선택 해제</button></span>:<span><MouseHint/>아이템을 선택한 뒤 장면 속 사물에 사용하세요.</span>}<span className="inventory-capacity">소지품은 자동으로 보관됩니다 <ShieldCheck size={12}/></span></div>
 <footer className="game-footer"><span className="footer-motto"><span className="tiny-diamond"/>{ko?'그의 말을 듣되, 당신의 눈을 믿으세요.':'Hear his words. Trust your eyes.'}</span><div><span><Clock3 size={13}/>{formatTime(g.data.playTime)}</span><span className="footer-dot">·</span><button onClick={()=>setPanel('help')}><Keyboard size={15}/>{ko?'조작 안내':'Controls'}</button><span className="footer-dot">·</span><span className="version-label">v.1.0 <span className="offline-dot"/> LOCAL SAVE</span></div></footer>
 </main>
 {g.toast&&<div className="toast" role="status"><CheckCheck size={17}/>{g.toast}</div>}
 {panel==='journal'&&<Modal title="정비 일지" eyebrow="PIN-04 · FIELD NOTES" onClose={close} wide><div className="modal-description">가이드의 말이 아닌, 직접 발견한 사실을 기록합니다.</div><div className="journal-toolbar"><div className="tab-group"><button className={journalTab==='evidence'?'active':''} onClick={()=>setJournalTab('evidence')}>관찰 기록 <span>{g.data.evidence.length}</span></button><button className={journalTab==='memories'?'active':''} onClick={()=>setJournalTab('memories')}>기억 조각 <span>{g.data.logs.length}</span></button></div><label className="search-field"><Search size={15}/><input value={journalSearch} onChange={e=>setJournalSearch(e.target.value)} placeholder="기록 검색"/></label></div><div className="journal-entries">{journalTab==='evidence'?(g.data.evidence.length===0?<div className="empty-state"><BookOpen size={35}/><h3>아직 펼치지 않은 이야기</h3><p>장면 속 눈 모양의 조사 지점을 클릭하세요.<br/>발견한 증거가 이곳에 차곡차곡 쌓입니다.</p><button className="primary-button" onClick={()=>{close();g.inspect();}}>첫 번째 장치 조사하기 <Eye size={16}/></button></div>:g.data.evidence.filter(e=>(e.text+stages[e.stage-1].title).includes(journalSearch)).slice().reverse().map(e=><article className="journal-entry" key={`${e.stage}-${e.step}`}><span className="entry-number">{String(e.stage).padStart(2,'0')}</span><div><div className="entry-meta">CHAPTER {stages[e.stage-1].regionId} <span>·</span> 직접 관찰한 증거 <Check size={12}/></div><h3>{stages[e.stage-1].title}</h3><p>{e.text}</p><button onClick={()=>{g.enter(e.stage);close();}}>이 장소로 돌아가기 <ArrowRight size={13}/></button></div></article>)):<><div className="memory-explanation"><Sparkles size={18}/><p>서로 다른 장소의 기억 10개를 모으면 마지막 안내탑에서 관리자 경로를 해독할 수 있습니다. <strong>{g.data.logs.length} / 10</strong></p></div>{g.data.logs.length===0?<div className="empty-state"><Sparkles size={34}/><h3>바닥의 작은 이야기를 찾아보세요</h3><p>모든 장면에는 빛바랜 기억 조각이 하나씩 숨겨져 있습니다.</p></div>:g.data.logs.filter(id=>stages[id-1].title.includes(journalSearch)).map(id=><article className="journal-entry" key={id}><span className="entry-number"><Sparkles size={22}/></span><div><div className="entry-meta">MEMORY {String(id).padStart(2,'0')}</div><h3>{stages[id-1].title}</h3><p>“안내는 선택을 대신하기 위해 만들어진 것이 아니다.”</p><button onClick={()=>{g.enter(id);close();}}>기록을 발견한 장소 <ArrowRight size={13}/></button></div></article>)}</>}</div></Modal>}
 {panel==='map'&&<Modal title="열 개의 지역, 하나의 여정" eyebrow="THE WORLD OF DECEPTIVE GUIDE" onClose={close} wide><div className="map-summary"><span>발견한 길은 언제든 다시 걸을 수 있습니다.</span><span><Flag size={14}/><strong>{completeCount}</strong> / 50 완료</span></div><div className="region-grid">{regions.map((r,index)=>{const start=index*5+1,unlocked=start<=maxStage;return <article className={`region-card ${unlocked?'':'region-locked'} ${g.stage.regionId===index+1?'current-region':''}`} key={r.name}><div className="region-card-image" style={{backgroundImage:`url(/images/region-${index+1}.jpg)`}}><span className="region-index">{String(index+1).padStart(2,'0')}</span>{!unlocked&&<LockKeyhole className="region-lock" size={24}/>} {g.stage.regionId===index+1&&<span className="current-location"><MapPin size={11}/> 현재 위치</span>}</div><div className="region-card-content"><h3>{r.name}</h3><p>{r.subtitle}</p><div className="stage-buttons">{Array.from({length:5},(_,n)=>start+n).map(id=><button key={id} disabled={id>maxStage} className={id===g.data.stage?'current':g.data.progress[id]?.completed?'finished':''} onClick={()=>{g.enter(id);close();}} title={stages[id-1].title}>{g.data.progress[id]?.completed?<Check size={13}/>:String(id).padStart(2,'0')}</button>)}</div></div></article>;})}</div></Modal>}
 {panel==='hint'&&<Modal title="정비 기록을 펼치다" eyebrow="AN HONEST HINT · NOT FROM TUTO-9" onClose={close}><div className="hint-stage"><Lightbulb size={20}/><span>{g.stage.title}<small>{g.puzzle.name}</small></span><span className="hint-level">{Math.max(1,g.hintLevel)} / 3</span></div><p className="modal-description">PIN-04가 남긴 정비 기록입니다. 한 번에 한 걸음씩, 직접 발견할 여지를 남겨 둡니다.</p><div className="hint-cards">{[1,2,3].map(level=><div className={`hint-card ${g.hintLevel>=level?'revealed':''}`} key={level}><span className="hint-number">0{level}</span><div><h3>{level===1?'주변을 관찰하기':level===2?'서로 다른 증거 비교하기':'행동의 원리 찾기'}</h3><p>{g.hintLevel<level?'아직 열지 않은 정비 기록':level===1?`「${g.puzzle.name}」 주변의 마모 자국, 연결선, 움직임을 조사해 보자. 눈 모양 조사 지점에서 기록을 얻을 수 있다.`:level===2?'TUTO-9의 안내와 직접 조사한 기록을 나란히 비교하자. 라벨보다 실제로 이어진 연결과 반복되는 현상이 중요하다.':g.puzzle.kind==='item'?'바닥에서 도구를 주운 뒤 인벤토리에서 선택하자. 도구의 형태와 장치의 홈이 맞는 대상에 사용한다.':g.puzzle.kind==='wait'?'한 번 작동한 후에는 손을 떼고 압력 반응을 지켜보자. 재작동하면 기다린 시간이 초기화된다.':g.puzzle.kind==='timing'?'주기 표시에서 발판이 연결되었다는 문구가 나타나는 동안 이동한다. 설정에서 안전 구간을 넓힐 수 있다.':g.puzzle.kind==='sequence'?'정비 일지에 기록한 물리적 흐름의 처음부터 차례대로 입력하자. 잘못 누르면 처음부터 다시 시작한다.':g.puzzle.kind==='balance'?'상자는 각각 한 번씩 올릴 수 있다. 기준 추와 무게의 합이 같아지면 저울 확인을 누르자.':'조사 기록에서 잠금장치로 실제 이어지는 대상, 또는 흔적과 일치하는 대상을 작동하자. 안내와 무조건 반대로 행동할 필요는 없다.'}</p></div>{g.hintLevel<level&&<LockKeyhole size={15}/>}</div>)}</div><div className="modal-footer"><span>힌트 사용은 진행을 막지 않습니다.</span>{g.hintLevel<3?<button className="primary-button" onClick={g.hint}>다음 기록 펼치기 <ChevronRight size={16}/></button>:<button className="primary-button" onClick={()=>{g.inspect();close();}}>장면을 다시 조사하기 <Eye size={16}/></button>}</div></Modal>}
 {panel==='inventory'&&<Modal title="작은 로봇의 소지품" eyebrow="PIN-04 · TOOL POUCH" onClose={close}><p className="modal-description">도구를 선택하고 장면 속 사물을 클릭해 사용하세요. 사용한 도구의 흔적도 단서가 됩니다.</p><div className="inventory-grid">{g.data.inventory.map((item,index)=><button key={item} className={g.selectedItem===item?'selected':''} onClick={()=>{if(item==='정비 수첩'){setPanel('journal');return;}g.selectItem(item);close();}}><span className="inventory-item-index">{String(index+1).padStart(2,'0')}</span><ItemArt name={item}/><strong>{item}</strong><small>{g.selectedItem===item?'선택됨':'선택하여 사용'}</small></button>)}</div><div className="item-tip"><Wrench size={17}/><p>아이템 이름을 믿기 어렵다면, 형태와 사용 흔적을 관찰하세요.</p></div></Modal>}
 {panel==='settings'&&<Modal title="당신에게 맞는 모험" eyebrow="SETTINGS & ACCESSIBILITY" onClose={close}><div className="settings-scroll"><h3 className="settings-section-title">소리와 화면</h3><Toggle label="효과음" description="작은 전자음과 장치의 반응" checked={settings.sound} onChange={()=>setting('sound',!settings.sound)}/><Toggle label="공간의 소리" description="낮고 잔잔한 기계의 공명" checked={settings.music} onChange={()=>setting('music',!settings.music)}/><Toggle label="고대비 · 색상 보조" description="선명한 윤곽과 글자 · 색상은 기호와 함께 표시" checked={settings.contrast} onChange={()=>setting('contrast',!settings.contrast)}/><Toggle label="큰 글자" description="대화와 정비 기록을 더 편하게 읽기" checked={settings.largeText} onChange={()=>setting('largeText',!settings.largeText)}/><Toggle label="움직임 줄이기" description="장식 애니메이션과 입자 효과 끄기" checked={settings.reduced} onChange={()=>setting('reduced',!settings.reduced)}/><h3 className="settings-section-title">플레이 접근성</h3><Toggle label="여유로운 기계 주기" description="타이밍 퍼즐의 안전 구간 넓히기" checked={settings.slow} onChange={()=>setting('slow',!settings.slow)}/><Toggle label="조사 대상 항상 표시" description="모든 조사 지점과 아이템에 이름 표시" checked={settings.showHotspots} onChange={()=>setting('showHotspots',!settings.showHotspots)}/><label className="language-setting"><span><Globe2 size={17}/> 인터페이스 언어</span><select value={settings.language} onChange={e=>setting('language',e.target.value as 'ko'|'en')}><option value="ko">한국어</option><option value="en">English · interface</option></select></label><h3 className="settings-section-title">오프라인 플레이</h3><p className="settings-note">현재 장면은 자동 보관됩니다. 전체 지역을 다운로드하면 네트워크 없이 여정을 이어갈 수 있습니다.</p><div className="offline-buttons"><button className="secondary-button" disabled={downloading>0} onClick={()=>void downloadRegion(false)}><ArrowDownToLine size={16}/>현재 지역</button><button className="secondary-button" disabled={downloading>0} onClick={()=>void downloadRegion(true)}><Download size={16}/>{downloading?`저장 중 ${downloading}%`:'전체 10개 지역 다운로드'}</button></div><div className="reset-section">{confirmReset?<><p>모든 진행 기록을 지우고 첫 교육실에서 시작할까요?</p><div><button className="danger-button" onClick={()=>{g.reset();setConfirmReset(false);close();}}>새 모험 시작</button><button className="secondary-button" onClick={()=>setConfirmReset(false)}>취소</button></div></>:<button className="text-button" onClick={()=>setConfirmReset(true)}><RotateCcw size={14}/>처음부터 다시 시작</button>}</div>{import.meta.env.DEV&&<div className="dev-tools"><strong>Development · Stage Selector</strong><select aria-label="Development Stage Selector" value={g.data.stage} onChange={e=>{g.enter(Number(e.target.value));close();}}>{stages.map(s=><option key={s.stageId} value={s.stageId}>{s.stageId}. {s.title}</option>)}</select><code>{JSON.stringify(validateStages())}</code></div>}</div></Modal>}
 {panel==='save'&&<Modal title="여정은 기억됩니다" eyebrow="SAVE & CONTINUE" onClose={close}><div className="save-card"><img src={g.stage.backgroundBundle} alt="현재 지역"/><div><span className="eyebrow">AUTOSAVE · LOCAL</span><h3>{g.stage.title}</h3><p>{region.name} · 스테이지 {g.data.stage} / 50</p><span><Clock3 size={13}/>{formatTime(g.data.playTime)} <span>·</span><Sparkles size={13}/>{g.data.logs.length} 기억 조각</span></div><ShieldCheck size={27}/></div><p className="modal-description">이동, 발견한 단서, 퍼즐 상태와 가이드의 행동 변형은 이 기기에 자동으로 저장됩니다. 다른 브라우저와는 공유되지 않습니다.</p><div className="save-actions"><button className="primary-button" onClick={()=>{void g.save();close();}}><Save size={16}/>지금 저장하기</button><button className="secondary-button" onClick={async()=>{const backup=await restoreBackup();if(backup){g.setData(backup);g.setDialogue({speaker:'PIN-04',tone:'clue',text:'저장한 위치로 돌아왔다. 남겨 둔 정비 기록을 다시 확인하자.'});g.notify('마지막 저장 기록을 불러왔습니다.');close();}else g.notify('이 기기에 불러올 백업 기록이 없습니다.');}}><FolderOpen size={16}/>최근 저장 불러오기</button></div></Modal>}
 {panel==='help'&&<Modal title="작은 발걸음부터" eyebrow="HOW TO PLAY" onClose={close}><div className="help-characters"><Pin/><span>관찰하고.<br/>의심하고.<br/><em>스스로 선택하세요.</em></span><Tuto/></div><div className="controls-list">{[['이동','장면의 바닥 클릭 / 방향키'],['상호작용','물체 클릭 / Tab → Enter'],['주변 조사','E · 조사 기록은 일지에 보관'],['조사 대상 표시','Space · 바닥에 포커스가 없을 때'],['인벤토리','I · 아이템 선택 후 대상 클릭'],['정비 일지 / 지도','J / M'],['정비 기록 힌트','H · 최대 3단계'],['화면 닫기','Esc']].map(([label,key])=><div key={label}><span>{label}</span><kbd>{key}</kbd></div>)}</div><p className="help-note"><Lightbulb size={17}/>가이드의 말은 공식 힌트가 아닙니다. 실패해도 괜찮아요. 관찰한 사실과 소지품은 사라지지 않습니다.</p><button className="primary-button help-start" onClick={close}>모험으로 돌아가기 <Play size={15}/></button></Modal>}
 {g.ending!==null&&<Modal title={g.ending===-1?'마지막 선택은, 당신의 것':endings[g.ending].title} eyebrow={g.ending===-1?'THE FINAL TUTORIAL':endings[g.ending].subtitle} onClose={()=>g.setEnding(null)} wide>{g.ending===-1?<><p className="ending-intro">안내는 끝났다. 전선과 기억이 가리키는 진실을 따라, PIN-04가 직접 길을 선택한다.</p><div className="ending-choices">{endings.map((e,index)=><button key={e.title} onClick={()=>g.finish(index)} className={index===2?'truth-choice':''}><span className="ending-choice-number">0{index+1}</span><div><h3>{['TUTO-9를 믿고 순응한다','TUTO-9를 완전히 종료한다','거짓말 모듈만 제거한다','도시의 안내 시스템을 해방한다'][index]}</h3><p>{['추천 출구 · 교육실로 돌아가는 연결','금지 출구 · 주 전원 차단','유지보수 통로 · 유리 인장으로 모듈 분리',`숨겨진 관리자 접점 · 기억 ${g.data.logs.length} / 10개`][index]}</p></div>{index===3&&g.data.logs.length<10?<LockKeyhole size={19}/>:<ArrowRight size={19}/>}</button>)}</div></>:<><div className={`ending-art ending-${g.ending}`} style={{backgroundImage:`url(/images/region-${g.ending===0?1:g.ending===1?9:4}.jpg)`}}><Pin pose="victory"/>{g.ending!==1&&<Tuto pose="idle"/>}<span>{g.ending===3?'EVERY PATH IS YOURS':g.ending===2?'TOGETHER, WITHOUT A MAP':g.ending===1?'A QUIET GOODBYE':'WELCOME BACK, PIN-04'}</span></div><p className="ending-text">{endings[g.ending].text}</p><div className="ending-footer"><span><Flag size={15}/>발견한 엔딩 {g.data.endings.length} / 4</span><button className="secondary-button" onClick={()=>g.setEnding(-1)}>다른 연결 살펴보기 <ArrowLeft size={15}/></button><button className="primary-button" onClick={()=>{g.setEnding(null);setPanel('map');}}>여정 돌아보기 <BookOpen size={15}/></button></div></>}</Modal>}
 </div>;
}
function MouseHint(){return <svg width="13" height="14" viewBox="0 0 14 16" fill="none" aria-hidden="true"><rect x="3" y="1" width="8" height="13" rx="4" stroke="currentColor"/><path d="M7 2V6M3 6H11" stroke="currentColor"/></svg>;}
